#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Apr 21 05:38:44 PDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit).zip
