raevyxSpawnWeight = 1
raevyxMinGroupSize = 1
raevyxMaxGroupSize = 1
raevyxAdditionalBiomes = []
raevyxExcludedBiomes = []
stegonautSpawnWeight = 1
stegonautMinGroupSize = 1
stegonautMaxGroupSize = 1
stegonautAdditionalBiomes = []
stegonautExcludedBiomes = []
cindervaneSpawnWeight = 1
cindervaneMinGroupSize = 1
cindervaneMaxGroupSize = 1
cindervaneAdditionalBiomes = []
cindervaneExcludedBiomes = []
cindervaneEggBlockWorldgen = true
nulljawSpawnWeight = 1
nulljawMinGroupSize = 1
nulljawMaxGroupSize = 1
nulljawAdditionalBiomes = []
nulljawExcludedBiomes = []
nulljawEggBlockWorldgen = true
ignivorusSpawnWeight = 1
ignivorusMinGroupSize = 1
ignivorusMaxGroupSize = 1
ignivorusAdditionalBiomes = []
ignivorusExcludedBiomes = []
ivyRestockInterval = 24000
